title = "toredis"

[listen]
address = "0.0.0.0:8712"

[logger]
log_path = "./toredis_error.log"
max_age = 7
max_size = 100
max_backup = 1

[redis]
db = 0
password = ""
pool_size = ""
redis_cluster = [
    "192.168.168.1",
    "192.168.168.2",
    "192.168.168.3",
]
